import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1[0], a1[1], a1[4])
a2 = np.array([[1,2], [3,4], [5,6]])
print("Dimension of a2 array is: ",a2.ndim)
print("Dimension of a1 array is: ",a1.ndim)
print("item size of a2 array is: ",a2.itemsize)
print("item size of a1 array is: ",a1.itemsize)
print("Data type of a2 array is: ",a2.dtype)
print("Data type of a1 array is: ",a1.dtype)
a2=np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
print("Data type of a2 array is: ",a2.dtype)
print("Data type of a1 array is: ",a1.dtype)
print("Shape of a2 array is: ",a2.shape)
print("Shape of a1 array is: ",a1.shape)


print("Zero array with dimension\n",np.zeros((2,3)))
print("Ones array with dimension\n",np.ones((2,3)))
print("Empty array with dimension\n",np.empty((2,3)))

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.arange(1,10).reshape(3,3))

print("Linearly spaced array\n",np.linspace(1,10,10))
print("Linearly spaced array\n",np.linspace(1,10,9).reshape(3,3))

print("Any dimension array can be shown in One dimension using this function: ",np.ravel(a2))
print("But its never touch the orginal array\n",a2)

print("Minum value of a2 array is: ",np.min(a2))
print("Maxum value of a2 array is: ",a2.max())
print("Sum of a2 array is: ",a2.sum())
print("Sum of a2 array azix=0 (1+3+5,2+4+6) is: ",a2.sum(axis=0))
print("Sum of a2 array azix=1 (1+2,3+4,5+6) is: ",a2.sum(axis=1))
print("Mean of a2 array is: ",a2.mean())
print("Square root of a2 array is:\n ",np.sqrt(a2))
print("Standard deviation of a2 array is: ",np.std(a2))
print("Variance of a2 array is: ",np.var(a2))
print("Exponential of a2 array is:\n",np.exp(a2))
print("Logarithm of a2 array is:\n",np.log(a2))
print("Logarithm of a2 array with base 10 is:\n",np.log10(a2))
print("Logarithm of a2 array with base 2 is:\n",np.log2(a2))
print("Square of a2 array is:\n",np.square(a2))


b = np.array([[1,2], [3,4]])
c = np.array([[5,6], [7,8]])
print("Addition of two arrays:\n",np.add(b,c))
print("Addition of two arrays:\n",b+c)
print("Subtraction of two arrays:\n",np.subtract(b,c))
print("Subtraction of two arrays:\n",b-c)
print("Multiplication of two arrays:\n",np.multiply(b,c))
print("Multiplication of two arrays:\n",b*c)
print("Division of two arrays:\n",np.divide(b,c))
print("Division of two arrays:\n",b/c)
print("Power of two arrays:\n",np.power(b,c))
print("Power of two arrays:\n",b**c)
print("Matrix dot product of two arrays:\n",np.dot(b,c))
print("Matrix dot product of two arrays:\n",b.dot(c))
print("Matrix transpose of b array:\n",np.transpose(b))
print("Matrix transpose of b array:\n",b.T)
